### ISSUE TITLE
Update to bootrap v4

### ISSUE THREAD

**Issue by albertyw** [albertyw/reaction-pics#42]

**Comment by cdlewis** [comment]
Have you considered material design?

**Comment by albertyw** [comment]
I actually would prefer flat design, e.g. http://designmodo.github.io/Flat-UI/

I would not be opposed to getting rid of bootstrap since the site uses like 5% of its features.

**Comment by albertyw** [comment]
Fixed in f9e7743

**Comment by cdlewis** [comment]
Thanks for the update
