### ISSUE TITLE
Cannot interact with content on reaction.pics

### ISSUE THREAD

**Issue by cdlewis** [albertyw/reaction-pics#50]
I'm guessing this is due to you adding the net neutrality banner. I'm not seeing the banner but there is a transparent iframe overlay across the entire page.

**Comment by albertyw** [comment]
Supposedly the new banner has some problems with some browser plugins.  No js errors were reported though.  

PRs accepted

**Comment by albertyw** [comment]
Fixed in ae2a2f47dbce579e42aeb3f2b0220dbdb4c5efc3 as suggested in https://github.com/fightforthefuture/battleforthenet-widget/issues/133
