### ISSUE TITLE
Deduplicate posts

### ISSUE THREAD

**Issue by albertyw** [albertyw/reaction-pics#84]
https://www.reaction.pics/post/72768527569/when-ive-been-working-on-an-ex
https://www.reaction.pics/post/71415361412/when-ive-been-working-on-an-ex

**Comment by cdlewis** [comment]
Can you add me to the PPP?

**Comment by albertyw** [comment]
Progress
 - Added issue
Problems
 - Nothing
Plans
 - Wait for @cdlewis to send me a PR

**Comment by albertyw** [comment]
Progress
 - Fixed in dc2adf3
Problems
 - None
Plans
 - Close task
